COUNTRY_CHOICES = [
    ('Albania', 'Albania'),
    ('Austria', 'Austria'),
    ('Belgium', 'Belgium'),
    ('Bosnia & Herzegovina', 'Bosnia & Herzegovina'),
    ('Croatia', 'Croatia'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('Germany', 'Germany'),
    ('Greece', 'Greece'),
    ('Italy', 'Italy'),
    ('Lithuania', 'Lithuania'),
    ('Montenegro', 'Montenegro'),
    ('Netherlands', 'Netherlands'),
    ('Norway', 'Norway'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Romania', 'Romania'),
    ('Serbia', 'Serbia'),
    ('Spain', 'Spain'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Turkey', 'Turkey'),
    ('United Kingdom', 'United Kingdom'),
]


