COUNTRY_CHOICES = [
    ('Albania', 'Albania'),
    ('Austria', 'Austria'),
    ('Belgium', 'Belgium'),
    ('Bosnia & Herzegovina', 'Bosnia & Herzegovina'),
    ('Bulgaria', 'Bulgaria'),
    ('Croatia', 'Croatia'),
    ('Cyprus', 'Cyprus'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Estonia', 'Estonia'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('Germany', 'Germany'),
    ('Greece', 'Greece'),
    ('Hungary', 'Hungary'),
    ('Ireland', 'Ireland'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jordan', 'Jordan'),
    ('Latvia', 'Latvia'),
    ('Lithuania', 'Lithuania'),
    ('Luxembourg', 'Luxembourg'),
    ('Malta', 'Malta'),
    ('Montenegro', 'Montenegro'),
    ('Morocco', 'Morocco'),
    ('Netherlands', 'Netherlands'),
    ('Norway', 'Norway'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Romania', 'Romania'),
    ('Serbia', 'Serbia'),
    ('Slovakia', 'Slovakia'),
    ('Spain', 'Spain'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Turkey', 'Turkey'),
    ('United Kingdom', 'United Kingdom'),
]
