# Generated by Django 5.2.7 on 2025-11-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure_country', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_city', models.CharField(max_length=50)),
                ('arrival_country', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_city', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('flight_type', models.CharField(choices=[('DOM', 'Domestic'), ('INT', 'International')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=50)),
                ('passenger_surname', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=11)),
                ('country_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('seat_class', models.CharField(choices=[('BASIC', 'Basic'), ('REGULAR', 'Regular'), ('PLUS', 'Plus')], max_length=10)),
                ('seat_number', models.CharField(blank=True, max_length=5, null=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=20)),
                ('extra_luggage', models.CharField(blank=True, max_length=30, null=True)),
                ('extra_equipment', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
