# Generated by Django 5.2.6 on 2025-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='country_code',
            field=models.CharField(default='HR', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
