# Generated by Django 5.2.7 on 2025-10-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_ticket_country_code_alter_ticket_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Refunded')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Canceled')], default='booked', max_length=10),
        ),
    ]
