# Generated by Django 5.2.7 on 2025-10-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_ticket_payment_status_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='baggage_allowance',
        ),
    ]
