# Generated by Django 5.2.7 on 2025-10-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_flight_baggage_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extra_equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='extra_luggage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
